name: Daily Commit Workflow

on:
  schedule:
    - cron: '30 5 * * *'  # Runs daily at 5:30 AM UTC
  workflow_dispatch:       # Optional: lets you run it manually

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: "Add commit for 23f2004818@ds.study.iitm.ac.in"
        run: |
          echo "Daily commit on $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily commit"
          git push
